version: "3"

services:
    mysql-camunda:
        image: mysql:5.6
        volumes:
            - camunda-data:/var/lib/mysql
        ports:
            - 3310:3306
        environment:
            MYSQL_ROOT_PASSWORD: changeme
            MYSQL_DATABASE: process_engine
            MYSQL_USER: dev
            MYSQL_PASSWORD: changeme
    camunda:
        image: camunda/camunda-bpm-platform:latest
        ports:
            - 8080:8080
        environment:
            DB_DRIVER: com.mysql.jdbc.Driver
            DB_USERNAME: dev
            DB_PASSWORD: changeme
            DB_URL: jdbc:mysql://mysql-camunda:3306/process_engine
            WAIT_FOR: mysql-camunda:3306
            WAIT_FOR_TIMEOUT: 120
        depends_on:
            - mysql-camunda
volumes:
    camunda-data: {}